<?xml version="1.0" encoding="utf-8"?><Database Name="Avia" Class="AviaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-50OOFA6;Initial Catalog=Avia;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AviaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Airport" Member="Airports">
    <Type Name="Airport">
      <Column Name="AirportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AirportName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tickets" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="TicketId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FlightId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeatNumber" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Flight_Ticket" Member="Flight" ThisKey="FlightId" OtherKey="flight1" Type="Flight" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Company_Plane" Member="Planes" ThisKey="CompanyID" OtherKey="CompanyID" Type="Plane" />
    </Type>
  </Table>
  <Table Name="dbo.Flights" Member="Flights">
    <Type Name="Flight">
      <Column Name="flight" Member="flight1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Plane" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Flight_Ticket" Member="Tickets" ThisKey="flight1" OtherKey="FlightId" Type="Ticket" />
      <Association Name="Plane_Flight" Member="Plane1" ThisKey="Plane" OtherKey="PlaneNum" Type="Plane" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Planes" Member="Planes">
    <Type Name="Plane">
      <Column Name="PlaneNum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InFlight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableSeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Plane_Flight" Member="Flights" ThisKey="PlaneNum" OtherKey="Plane" Type="Flight" />
      <Association Name="Company_Plane" Member="Company" ThisKey="CompanyID" OtherKey="CompanyID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
</Database>